apiVersion: v1
kind: BuildConfig
metadata:
  name: tour-of-heroes-chained-s2i
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: '2018-01-08T20:54:22Z'
  name: tour-of-heroes-chained-s2i
  namespace: myproject
  resourceVersion: '45008'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/myproject/buildconfigs/tour-of-heroes-chained-s2i
  uid: 1a6150a7-f4b6-11e7-a959-525400d2f593
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'tour-of-heroes-nginx:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM bitnami/nginx
      COPY dist/angular-tour-of-heroes/* /app/
      EXPOSE 8080
    images:
      - from:
          kind: ImageStreamTag
          name: 'tour-of-heroes-s2i:latest'
        paths:
          - destinationDir: .
            sourcePath: /opt/app-root/src/dist
          - destinationDir: .
            sourcePath: /opt/app-root/src/nginx
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'nginx:1.13.3-alpine'
    type: Docker
  triggers: []
status:
  lastVersion: 6
